force-app/main/default/objects/Contact/fields/CDC_CAC_Business_Email__c.field-meta.xml
<CustomField>
    <fullName>CDC_CAC_Business_Email__c</fullName>
    <label>Business Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CDC_CAC_Business_Trading_Name__c.field-meta.xml
<CustomField>
    <fullName>CDC_CAC_Business_Trading_Name__c</fullName>
    <label>Business Trading Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CDC_CAC_Consent_Given__c.field-meta.xml
<CustomField>
    <fullName>CDC_CAC_Consent_Given__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Consent Given</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CDC_CAC_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>CDC_CAC_Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CDC_CAC_First_Name_Native__c.field-meta.xml
<CustomField>
    <fullName>CDC_CAC_First_Name_Native__c</fullName>
    <label>First Name Native</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CDC_CAC_Integration_Id__c.field-meta.xml
<CustomField>
    <fullName>CDC_CAC_Integration_Id__c</fullName>
    <externalId>true</externalId>
    <label>Integration Id</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CDC_CAC_Interceptor_Flag__c.field-meta.xml
<CustomField>
    <fullName>CDC_CAC_Interceptor_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Interceptor Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CDC_CAC_Interceptor_Id__c.field-meta.xml
<CustomField>
    <fullName>CDC_CAC_Interceptor_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Interceptor Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/CDC_CAC_Interceptor_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>CDC_CAC_Interceptor_Timestamp__c</fullName>
    <label>Interceptor Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CDC_CAC_Last_Name_Native__c.field-meta.xml
<CustomField>
    <fullName>CDC_CAC_Last_Name_Native__c</fullName>
    <label>Last Name Native</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CDC_CAC_Title__c.field-meta.xml
<CustomField>
    <fullName>CDC_CAC_Title__c</fullName>
    <label>Title</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CDC_CAC_Title</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/CDC_CAC_VAT_Number__c.field-meta.xml
<CustomField>
    <fullName>CDC_CAC_VAT_Number__c</fullName>
    <label>VAT Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/CDC_CAC_Title.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Lady</fullName>
    </customValue>
    <customValue>
        <fullName>Sir</fullName>
    </customValue>
    <masterLabel>CDC CAC Title</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/customerController.cls
public with sharing class customerController {
@AuraEnabled(Cacheable=true)
public static Contact[] getAllCustomers() {
	return [SELECT Id, LastName, FirstName, Salutation, MailingStreet, MailingCity,
	        MailingState, MailingPostalCode, MailingCountry, MailingLatitude, MailingLongitude,
	        MailingGeocodeAccuracy, Phone, Fax, MobilePhone, HomePhone, OtherPhone,
	        AssistantPhone, Email, Title, AssistantName, Birthdate, CDC_CAC_Title__c,
	        CDC_CAC_Last_Name_Native__c, CDC_CAC_Business_Trading_Name__c, CDC_CAC_First_Name_Native__c,
	        CDC_CAC_VAT_Number__c, CDC_CAC_Business_Email__c, CDC_CAC_Interceptor_Id__c,
	        CDC_CAC_Interceptor_Flag__c, CDC_CAC_Interceptor_Timestamp__c, CDC_CAC_Consent_Given__c,
	        CDC_CAC_Expiration_Date__c, CDC_CAC_Integration_Id__c
	        FROM Contact ORDER BY Name LIMIT 50];
}

@AuraEnabled(Cacheable=true)
public static Contact[] searchCustomers(String[] searchTerm) {
	// Execute search query
	return [SELECT Id, LastName, FirstName, Salutation, MailingStreet, MailingCity,
	        MailingState, MailingPostalCode, MailingCountry, MailingLatitude, MailingLongitude,
	        MailingGeocodeAccuracy, Phone, Fax, MobilePhone, HomePhone, OtherPhone,
	        AssistantPhone, Email, Title, AssistantName, Birthdate, CDC_CAC_Title__c,
	        CDC_CAC_Last_Name_Native__c, CDC_CAC_Business_Trading_Name__c, CDC_CAC_First_Name_Native__c,
	        CDC_CAC_VAT_Number__c, CDC_CAC_Business_Email__c, CDC_CAC_Interceptor_Id__c,
	        CDC_CAC_Interceptor_Flag__c, CDC_CAC_Interceptor_Timestamp__c, CDC_CAC_Consent_Given__c,
	        CDC_CAC_Expiration_Date__c, CDC_CAC_Integration_Id__c
	        FROM Contact WHERE CDC_CAC_Integration_Id__c in : searchTerm LIMIT 50];
}
}